### PR TITLE
Changes made that enable flightplan cli to run with --docker flag

### PR DESCRIPTION
**Pull request by Fffrank**
Was able to get the --docker flag added to the CLI tool.  Didn't break anything in the process.  

Server and Client require that I'm able to modify the hostname of the proxy in packages.json.  I have not found a way to do that.  Would be ideal if I could either define a hostname during the "npm install" process or somehow from the command line?  Would love some input if you think of a way -- until then, I'll continue to push updated images to the hub.docker.com manually.

### CODE REVIEW

**Comment by jd20** [comment]
Thanks! Will take a look soon.

**Comment by Fffrank** [comment]
Awesome.  I also figured out a way to build the docker containers while replacing the localhost in client/package.json so nothing else required on your end.

This will allow the images to be built directly from your github every time (and should also allow me to automate it so that when you push new updates it builds new images.)

I'll work on adding a section to the readme on how to use these.

**Comment by Fffrank** [comment]
Feel free to use this (or edit and use this) too add to the readme.

https://github.com/Fffrank/flightplandocker/blob/master/README.md

**Comment by jd20** [comment]
Thanks! I'll add it as a new page under `/docs`, and link to it from the main README.

**Pull request merged**
